apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  containers:
    - env:
        - name: DB_HOST
          value: host.docker.internal
        - name: DB_NAME
          value: animal
        - name: DB_PASSWORD
          value: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: QUEUE_HOST
          value: host.docker.internal
        - name: QUEUE_NAME
          value: cat-dog-queue
        - name: QUEUE_PASSWORD
          value: guest
        - name: QUEUE_PORT
          value: "5672"
        - name: QUEUE_USER
          value: guest
      image: noneword/consumer-rabbitmq
      name: consumer
      ports:
        - containerPort: 4502
      resources: {}
  restartPolicy: OnFailure
status: {}
