apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit
    spec:
      containers:
        - image: rabbitmq:3.9-management
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics -q ping
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/
              name: rabbit-claim0
            - mountPath: /var/log/rabbitmq
              name: rabbit-claim1
      restartPolicy: Always
      volumes:
        - name: rabbit-claim0
          persistentVolumeClaim:
            claimName: rabbit-claim0
        - name: rabbit-claim1
          persistentVolumeClaim:
            claimName: rabbit-claim1
status: {}
